### ISSUE TITLE
Targeted file updates in Jp2 create

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/common-accessioning#1090]
In targeted file updates, the tiff file will not exist in the workspace if it has not changed. The Jp2Create robot expects it to exist so that a JP2 file can be generated at the cocina model updated.

Possible approaches:
* Ignore, tiff files will not be accessioned with Pre-assembly
* Require tiff files to be present so that Jp2Create can be run (i.e., they cannot be used with targeted file updates)
* In Pre-assembly, if a tiff file has not changed then add the cocina file for the JP2 into the structural. When the tiff file is not present, but there is a cocina file for the Jp2 in the structural, the Jp2Create robot does not attempt to generate a new Jp2.

Also needs to be considered how each of these approaches will affect shelving, which probably assumes that the Jp2 file is present.

Thoughts @andrewjbtw ?

**Comment by edsu** [comment]
This is waiting for feedback from @andrewjbtw

**Comment by lwrubel** [comment]
If I understand @justinlittman's PR correctly, if the page/image file is not present on the filesystem, then the jp2_create step just moves on. 

Is there more work or questions to be answered about this?

**Comment by lwrubel** [comment]
There is still the issue that when an image/page file is replaced, the jp2 for the previous version is getting used instead of a new one being generated.

**Comment by andrewjbtw** [comment]
We talked about this yesterday afternoon. I think there are multiple scenarios where the logic depends on:

- what the file_manifest.csv says
- what files are put on the filesystem

Case 1 

- new TIFF provided via Preassembly
- row for TIFF remains in CSV from the Argo download
- row for the old JP2 has been deleted from file_manifest.csv
- no JP2 is provided

I think we already support this case. What should happen is:

- jp2-create sees the TIFF in Cocina and on the filesystem, sees that there isn't a JP2 already, creates a new JP2

Case 2

- new TIFF provided via Preassembly
- row for the TIFF remains in the file_manifest.csv
- no JP2 is provided
- but there's still a row for the JP2 in the file_manifest.csv (even though the JP2 is not in preservation, it will be in the Argo CSV download, so will be there unless someone specifically deletes it)

In this situation, a new JP2 has to be created from the new TIFF. There has to be some logic to detect that:

- there is a TIFF on the filesystem
- there is no JP2 on the filesystem
- the TIFF on the filesystem should be used to create a new JP2, replacing the old one

I'm not sure it's necessary to detect if the TIFF has changed. The logic could be that if there's a TIFF on the filesystem and no corresponding JP2 on the filesystem, create a new JP2 from that TIFF.

Case 3

- no new TIFF provided via Preassembly
- row for TIFF remains in the file_manifest.csv
- no row is in the file_manifest.csv for a JP2
- no JP2 is provided

This is another tricky one. jp2-create will detect that there is no JP2, which will trigger an attempt to create the JP2 from the TIFF. But the TIFF will not be in the /dor/assembly space because it hasn't changed and wasn't staged for accessioning.

In this scenario, I would like the system to retrieve a copy of the JP2 from preservation and put it in /dor/assembly so that the JP2 can be created. That would be an entirely new bit of functionality but there is value in being able to generate JP2s from preserved files that extends beyond this targeted file update feature.

We do have a mechanism to pull files from preservation and put them on Stacks when someone changes "shelve=no" to "shelve=yes". That might offer an example for how to get files from preservation for jp2-create.

Case 4

- no new TIFF provided
- row for TIFF remains in file_manifest.csv from the Argo download
- no new JP2 provided
- row for JP2 remains in the file_manifest.csv

I believe the new targeted file update function already handles this case. No changes are made to the files.

Case 5

- new TIFF provided
- row for TIFF remains in file_manifest.csv from the Argo download
- new JP2 provided
- row for JP2 remains in the file_manifest.csv

We trust that the user knows what they're doing and the system takes the TIFF and JP2 files exactly as they are.

Case 6

- no new TIFF provided
- row for TIFF remains in file_manifest.csv from the Argo download
- new JP2 provided
- row for JP2 remains in the file_manifest.csv

In this case, the user provides a new JP2 but no TIFF. We trust that they know what they're doing and make the change to the JP2 without requiring any jp2-create processing of the TIFF.

**Comment by ndushay** [comment]
If the question is answered, can the label please be removed?
