### ISSUE TITLE
Update cocina when OCR complete

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1185]
part of #1166 
depends on #1177

Write implementation for `ocrWF:update-cocina` robot

We need to update the cocina (in a new robot in ocrWF) when OCRing is complete, and prior to accessioning content.  This is similar to how the cocina structural is generated by pre-assembly in [app/lib/pre_assembly/from_staging_location/structural_builder.rb](https://github.com/sul-dlss/pre-assembly/blob/main/app/lib/pre_assembly/from_staging_location/structural_builder.rb#L41-L52)

To simplify things this workflow step can determine what files need to be added by simply looking at what files have been placed in the workspace directory as part of #1177.

New cocina fields at the file level (in structural) will need to be added based on if accessioned content has already had OCR performed and when OCR is done by our new ABBYY based robots.

See https://docs.google.com/document/d/1ScvlgCI-YhyV2LaaDLTVOWTvuGe4bM1tmgzVbAHTDw8/edit#heading=h.og29aoqammz0 for details on the attributes, values and when set.

The values indicating when a file had OCR performed by ABBYY should presumably be set when the create-ocr robot has completed successfully.  The values indicating when a file had incoming provided OCR is also set in pre-assembly, but this will be set in the cocina elsewhere as part of sul-dlss/pre-assembly#1441

What ABBYY returns:
```
Images of text:
1 ALTO
1 PDF
1 plain-text

PDF:
1 PDF (unless otherwise determined that we need additional files)
```

We need to ensure that when cocina is generated, these files are added with the correct attributes so they are shelved, published and preserved correctly.

Ref May 16 notes: https://docs.google.com/document/d/1ADOY6Mr9pwVf2EUr2wb-dt8_KVUBxMSksrrcY5Qqi5o/edit#heading=h.8u9choka43a

**Comment by jmartin-sul** [comment]
We think this also might sort of depend on or overlap with #1177, so if two different people pick up these two tickets, they should maybe coordinate.

**Comment by jmartin-sul** [comment]
We think this is unblocked, because the new attributes are now available in a released version of cocina-models.

The overall idea is to take the newly generated OCR files and to do a targeted file update to the existing cocina structural without staging all of the files.

Whoever picks this up may want to look at H2 and/or pre-assembly and/or [GIS robot suite](https://github.com/sul-dlss/gis-robot-suite/blob/main/lib/robots/dor_repo/gis_assembly/generate_structural.rb) structural generation to see how partial file staging for update works there.  No one in the planning meeting right now is sure exactly where the existing logic for partial staging lives.

It may be best to split this ticket so that this one is about figuring out how to do this, and another follow-on is about actually implementing.  Or maybe it's all one ticket, TBD.

**Comment by peetucket** [comment]
For reference:

H2's structural generation code, which does appear to do diffing.  But H2 seems to build simple structure (one per per fileset):
- https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/structural/generator.rb
- https://github.com/sul-dlss/happy-heron/blob/main/app/services/cocina_generator/structural/file_generator.rb

Pre-assembly's structural generation code:
- https://github.com/sul-dlss/pre-assembly/blob/main/app/lib/pre_assembly/from_staging_location/structural_builder.rb
- https://github.com/sul-dlss/pre-assembly/blob/main/app/lib/pre_assembly/from_staging_location/file_set_builder.rb
