### ISSUE TITLE
Handle/Notify on ABBYY crashing

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1242]
ABBYY may sometimes crash unexpectedly (i.e. on being passed image content with no text, e.g. a photograph).  It may be helpful to notify on this.  Could be a nagios alert?  An HB alert via a monitoring process?

Questions:
- how do we know if ABBYY crashed? is there some process on the server that goes away?

**Comment by jmartin-sul** [comment]
> how do we know if ABBYY crashed? is there some process on the server that goes away?

probably a good question for @calavano and/or ops folks.

ABBYY is already in production for Goobi, so we're also wondering if there is any of this sort of monitoring already?

We can also see if there are files in ABBYY input directories that are too stale, which would be a symptom of ABBYY not processing things.  Or too many things stuck at the `ocr-create` step.

We could also add an okcomputer check to e.g. common-accessioning that watches queue depth for some step in `ocrWF`.  This might be easiest for infra folks to run with, since it would have no direct dependency on ABBYY itself, or other services we don't maintain ourselves.

**Comment by peetucket** [comment]
Note on the okcomputer approach: common-accessioning is the most obvious place that has access to the abbyy input folders, but it is also does not have okcomputer and is not a rails project, so there is no UI either.  So the okcomputer specific approach may not work (on common-accessioning at least)

**Comment by jmartin-sul** [comment]
> Note on the okcomputer approach: common-accessioning is the most obvious place that has access to the abbyy input folders, but it is also does not have okcomputer and is not a rails project, so there is no UI either. So the okcomputer specific approach may not work (on common-accessioning at least)

good point!
