### ISSUE TITLE
Technical metadata workers running out of memory for large books

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#311]
```
Resque::DirtyExit: Child process received unhandled signal pid 6097 SIGKILL (signal 9)
```

This is happening when this object: https://argo.stanford.edu/view/druid:wx632tb5379 , which has over 700 pages, is run through the technical metadata robot.  The process baloons to over 7G of memory (takes about 14 min) and then the OOM killer stomps it

**Comment by ndushay** [comment]
created sul-dlss/operations-tasks/issues/1993 asking for more memory ...

**Comment by ndushay** [comment]
Note that this is also related to a whole rethinking of technicalMetadata - what should we be generating -- can we simplify it?

**Comment by ndushay** [comment]
Apparently, this is not ONLY a single worker running out of memory on a single job ... it's also when a lot of workers are generating tech md at the same time -- as it is a RAM hungry process.

**Comment by ndushay** [comment]
sul-dlss/operations-tasks/issues/1993  was done;  common-accessioning boxes now all at 8 cores, 16GB.

**Comment by ndushay** [comment]
@andrewjbtw -- this may be address as the common-accessioning boxes have more RAM now!

**Comment by mjgiarlo** [comment]
@jcoyne @ndushay I can confirm that the changes made in https://github.com/sul-dlss/operations-tasks/issues/1993 are clearing up the OOM-related techMD errors. I've been re-running the techMD steps for objects with this error one-by-one, and have so far clearer seven or eight of them. Two to go. cc: @andrewjbtw

**Comment by mjgiarlo** [comment]
OK, I ran https://argo.stanford.edu/view/druid:jw486yh9643 and https://argo.stanford.edu/view/druid:zt138zy7677 at the same time, and both were  OOM-killed many hours later, fairly close to one another. These were running on different common-accessioning prod nodes, and no other workers were running at the same time. I saw the `Resque::DirtyExit` exception come through [honeybadger](https://app.honeybadger.io/projects/52894/faults/49396748) and the job failure popped up in the [Resque web UI](https://robot-console-prod.stanford.edu/failed/?class=Robots::DorRepo::Accession::TechnicalMetadata). So I'm not sure I'd say it's fixed for **all** of our data, I'm sad to report, @sul-dlss/infrastructure-team. Not sure what else we can do. Even moar resourcez? :unamused:

**Comment by jcoyne** [comment]
@mjgiarlo get rid of jhove? Use `identify` + `ffprobe`  instead?

**Comment by mjgiarlo** [comment]
Options discussed in the @sul-dlss/infrastructure-team slack channel earlier today:

1. increase worker box resources (this doesn't seem doable -- @julianmorley)
1. greatly reduce number of techMD workers (limits ingest throughput -- @andrewjbtw)
1. come up with a strategy for techMD that doesn't require memory hogs like JHOVE or FITS (seems like the winner among the bunch, but will require techMD requirements to be defined and also infra team time -- @vivnwong)
1. stop ingesting books/large files (not gonna happen)
1. Switch to cloud and pay for resources as we need/consume them. (this is prolly @jcoyne being :trollface:)

The Infra team will discuss this more in our next infra team dev meeting (on Oct. 15th).

**Comment by peetucket** [comment]
Option 2 seems the most viable for now. 

Or option 6 could be pre-generating techMD separately from the robots on a box with sufficient resources, placing the techMD xml file in the content to be accessioned and teaching the techMD robot to pick it up if exists.  This is how content-metadata and desc-metadata already work (i.e. you can pre-generate that datastream XML, store as a file and the robots will simply pick it up and add it to the object instead of trying to generate it).

**Comment by mjgiarlo** [comment]
@aaron-collier Here is the issue you may want to keep an eye on next week, as first responder.

**Comment by mjgiarlo** [comment]
Do we think #489 connects to this issue or may even fix/close it?

**Comment by jcoyne** [comment]
@mjgiarlo I don't think the two are related.

**Comment by justinlittman** [comment]
A little back-of-the-envelope analysis and then a suggestion.

XML output size from:
* TIFF from druid:wx632tb5379 (700 page book): 165K
* JP2 from druid:wx632tb5379: 361K
* HTML from google book: 104K
* JP2 from google book: 52K

The good news is that the techmd from google books may be smaller than some of our other large books. However, it seems like a bad idea to rely on this.

Rather than decide what we want to keep, it might be easier to decide what we don't want to keep. For each of these jhove outputs, a significant portion of their size is composed of a small number of large blocks of data. I would suggest that in most cases these blocks are low value and could be filtered out.

For example, if you remove copies of the DTDs included in (each and every) output for google book HTML, the file size goes from 104K to 7.1K.

**Comment by jcoyne** [comment]
We need to adopt a data model so we can switch away from Fedora 3, so choosing what we want to persist has benefits beyond just this out of memory issue.

**Comment by andrewjbtw** [comment]
Is the techmd here a good example of what we'll see for Google Books? 
https://argo-stage.stanford.edu/view/druid:dr934br2164

I'm not seeing copies of the DTD, but there are a ton of messages in the ``` <jhove:messages>``` element saying with the HTML is not valid XHTML, and I don't see why we need to keep that. We're not going to make the HTML valid. 

I don't know if <jhove:messages> ever has useful information, given that we're not actually going to use it within the system to fix files. I think we can safely exclude it.

**Comment by peetucket** [comment]
Pending updating our method of technical Metadata generation.

**Comment by ndushay** [comment]
I assume this ticket can be closed now?   Also - are we now hogging more memory than we need?

**Comment by mjgiarlo** [comment]
@sul-dlss/infrastructure-team :point_up:

**Comment by justinlittman** [comment]
This is for JHOVE-based techmd, so closing.
