### ISSUE TITLE
Bump version of assembly-image once issue 24 is closed and new version is available

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/common-accessioning#363]
```
RuntimeError: JP2 creation command failed: kdu_compress -num_threads 2 -precise -no_weights -quiet Creversible=no Cmodes=BYPASS Corder=RPCL Cblk=\{64,64\} Cprecincts=\{256,256\},\{256,256\},\{128,128\} ORGgen_plt=yes -rate 1.5 Clevels=5 Clayers=7 -i '/dor/assembly/tb/007/bv/0937/tb007bv0937/content/tb007bv0937_01.tif' -o '/dor/assembly/tb/007/bv/0937/tb007bv0937/content/tb007bv0937_01.jp2' 2>&1 with result Error in Kakadu File Format Support:
Attempting to write a colour description (colr) box which uses JPX extended
features to the image header of a baseline JP2 file.  You might like to upgrade
the application to write files using the `jpx_target' object, rather than
`jp2_target'.
```
## Backtrace

    line 51 of [PROJECT_ROOT]/lib/robots/dor_repo/assembly/jp2_create.rb: create_jp2
    line 32 of [PROJECT_ROOT]/lib/robots/dor_repo/assembly/jp2_create.rb: block in create_jp2s
    line 29 of [PROJECT_ROOT]/lib/robots/dor_repo/assembly/jp2_create.rb: each

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/52894/faults/50002691)

**Comment by jcoyne** [comment]
@calavano Do you know what might be causing this error?

**Comment by calavano** [comment]
This error is happening because of the input tiff being formatted in a way that would require the jpeg2000 file being made using Part 2 of the JPEG2000 specs, hence the JPX. Kakadu throws this error when you specify the output file as .jp2 instead of .jpx. This started showing up after we changed the behavior in the assembly-image to skip the conversion of an uncompressed tiff to the temporary tiff. I feel that the best thing to do would be reverting back to the behavior of always creating the temporary tiff as this normalizes the images into a format known to be safe for a JP2 file that stays within Part 1 of the specs.

I have a branch for assembly-image that reverses the change (as well as a fix that should get tiffs with >4GB of image data working), https://github.com/sul-dlss/assembly-image/tree/issue24

**Comment by mjgiarlo** [comment]
@calavano Do you think we could close this issue given that we already have https://github.com/sul-dlss/assembly-image/issues/24 written up? Once https://github.com/sul-dlss/assembly-image/issues/24 is closed and a new version with the changes are released, we can bump the version of `assembly-image` in `common-accessioning` and push out updates to stage and prod.

Alternatively, we can re-frame this issue as "Bump version of assembly-image once issue 24 is closed and new version is available," or some such, to track that latter work.

What do you think?

**Comment by calavano** [comment]
I like the 2nd option, renaming for clarity and keeping this open until the changes are pushed to production.

**Comment by mjgiarlo** [comment]
@calavano Done, I've re-titled this issue and created a new PR to bump the version to 1.7.6: https://github.com/sul-dlss/assembly-image/pull/26

**Comment by mjgiarlo** [comment]
@calavano 	I've redeployed common-accessioning to stage and prod with your changes in assembly-image. Shall we close the issue? Any verification we should do beforehand?

**Comment by calavano** [comment]
@mjgiarlo I've reset ~200 objects in a few batches and they're now passing through jp2-create without error and getting successfully accessioned. All signs point to this being fixed.

**Comment by mjgiarlo** [comment]
@calavano 	Excellent! I will close the issue. Feel free to re-open or open a new issue should this crop up again.
