### ISSUE TITLE
Switch robots to sidekiq?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/common-accessioning#902]
Consider implications of automatic retries

- common-accessioning (each workflow)
- preservation robots (John has concerns for pres robots thread safety ... or is that for replication?)
- gis robots
- was robots (?) - see web archiving work cycle
- robot-console

See #319 for more information

**Comment by ndushay** [comment]
From #662:

> This ticket comes out of discussion around [sul-dlss/google-books#471](https://github.com/sul-dlss/google-books/issues/471)
> 
> Switching to sidekiq would give us the benefit of automatic retries for workflow steps that encounter transient errors that clear up when the step is simply re-run a few moments later.
> 
> If we make this change for all workflow steps, we need to watch out for:
> 
>     1. Errors that won't clear up with a re-run (i.e. data needs to be fixed before re-run)
> 
>     2. Steps where re-running after an error results in a new error message that overwrites the original one.
> 
> 
> There are probably other things to watch out for. This ticket is to figure that out.

**Comment by justinlittman** [comment]
Here are the tasks that would be needed to switch to sidekiq and consolidate the robots in a single repository:
- [ ] Create new, consolidated repository.
  - [ ] Merge code from lybercore
  - [ ] Merge code from common accessioning
  - [ ] Merge code from pres robots
  - [ ] Merge code from GIS robots
  - [ ] Merge code from WAS robots
  - [ ] Add to dependency updates
  - [ ] Add to circleci
  - [ ] Add to codeclimate
- [ ] Update workflow server rails to enque to Sidekiq. See https://github.com/sul-dlss/workflow-server-rails/pull/626 
- [ ] Update puppet for all workers so that support Sidekiq. See https://github.com/sul-dlss/puppet/pull/9090
- [ ] Update shared_configs for all worker servers to include `redis_url` and `sidekiq*.yml` files.
- [ ] Switch robots console to serve Sidekiq web console
- [ ] Update DevOpsDocs.
- [ ] Deprecate legacy repositories.

**Comment by ndushay** [comment]
@justinlittman will you please close this ticket when ready?  Thank you.

**Comment by justinlittman** [comment]
Done, until there is a problem then it is not done.
